### ISSUE TITLE
Feature Request: Integration with ASE

### ISSUE THREAD

**Issue by ichibha** [shry-project/SHRY#6]
It would be greatly appreciated if structures could be obtained as an array of ASE's Atoms. Since VASP is frequently paired with ASE, implementing this feature could lead to wider application of SHRY.

**Comment by kousuke-nakano** [comment]
Dear @ichibha, thank you for your request. I will try to implement it.

**Comment by kousuke-nakano** [comment]
Dear @ichibha, I have an idea for implementing this. Would you help me?

I need a function to convert a `pymatgen structure` to the corresponding `ASE atoms` such as:

`from pymatgen_struct_to_ase_atoms(structure: pymatgen's structure) -> atoms: ASE's atoms`

Would you try to implement it?

**Comment by ichibha** [comment]
@kousuke-nakano Thank you for your willingness to work on this issue. The pymatgen Structure object can be converted into an ASE Atoms object using the following function:

```python
from pymatgen.core import Structure
from ase import Atoms


def pymatgen_struct_to_ase_atoms(structure: Structure) -> Atoms:
    return Atoms(
        symbols=[specie.symbol for specie in structure.species],
        positions=structure.cart_coords,
        cell=structure.lattice.matrix,
        pbc=True,
    )


if __name__ == "__main__":
    for label in ["cartesian", "fractional"]:
        structure = Structure.from_file(f"{label}.vasp")
        atoms = convert_structure_to_atoms(structure)
        atoms.write(f"{label}_converted.vasp")
```

I attach the files used to verify the code. 


[submit.zip](https://github.com/shry-project/SHRY/files/14099341/submit.zip)

**Comment by kousuke-nakano** [comment]
Dear @ichibha, Thanks. I have implemented it. Would you have a look at my pull request #7? I have added a new example `example5.py`. I would appreciate if you would confirm that SHRY works as you expected.

**Comment by ichibha** [comment]
Dear @kousuke-nakano, Thank you for your correspondence. The code works as I expected. I will make a suggestion with my expected behavior from the next time.

**Comment by kousuke-nakano** [comment]
Dear @ichibha, thanks. We will include this feature to the next release.
