### ISSUE TITLE
AttributeError: np.deprecate

### ISSUE THREAD

**Issue by artemichi1297** [shry-project/SHRY#8]
Hello
I encountered the following error when I tried running SHRY:

>AttributeError: `np.deprecate` was removed in the NumPy 2.0 release. Emit `DeprecationWarning` with `warnings.warn` directly, or use `typing.deprecated`.

I installed SHRY from here using "git clone"
I tried reinstalling NumPy, however it did not help. Currently I have numpy-2.1.1

**Comment by kousuke-nakano** [comment]
Dear @artemichi1297, thank you very much! Would you try to downgrade `numpy` < 2?

**Comment by artemichi1297** [comment]
Dear @kousuke-nakano, after downgrading numpy it works just fine. Thanks!

**Comment by kousuke-nakano** [comment]
@artemichi1297 OK!
