### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hongo-lab** [shry-project/SHRY#9]
When generating a supercell via:
    shry --scaling-matrix="3 3 3" [cif]
I got the following error:
%------------------
...
  File "<path to>/shry/lib/python3.12/site-packages/shry/main.py", line 762, in read_label
    parser = CifParser.from_string(f.read())
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CifParser' has no attribute 'from_string'. Did you mean: 'from_str'?
%------------------

I guess 'CifParser' comes from pymatgen. 
For your reference, my pymatgen version is:
    pymatgen==2024.10.3
    
To avoid this error, which pymatgen is appropriate for the shry?

Thank you for your help in advance.

**Comment by kousuke-nakano** [comment]
Dear @hongo-lab, thank you for your inquiry. As written in `setup.cfg`, the supported `pymatgen` versions are `pymatgen` >= 2019.1.13, <= 2023.10.4. I wonder if you installed `SHRY` via `pip`. If so, the version compatibility should be automatically handed by `pip`.

**Comment by kousuke-nakano** [comment]
Dear @hongo-lab, I wonder if you still have the incompatibility problem. Please let me know.

**Comment by hongo-lab** [comment]
Thank you for the information regarding the installation. Instead of installing it directly on my Mac, I decided to use a container environment, so the issue has been resolved.

**Comment by kousuke-nakano** [comment]
@hongo-lab, thank you very much. I close the issue.
